A:
	gcc -W -Wall -O2 -ansi -pedantic -g A.c -o output
	./checkprac2 ./output -d lab13a
B:
	gcc -W -Wall -O2 -ansi -pedantic -g B.c -o output
	./checkprac2 ./output -d lab13b
C:
	gcc -W -Wall -O2 -ansi -pedantic -g C.c -o output
	./output
	./checkprac2 ./output -d lab13c
